### ISSUE TITLE
could you please write some wiki to explain how to use it?

### ISSUE THREAD

**Issue by archonwang** [eckucukoglu/redmine-reminder-emails#1]
could you please write some wiki to explain how to use it?
Thanks.

**Comment by eckucukoglu** [comment]
hi steven, I have updated readme at cfe8d8369fee1be5cca5aaf714f5a1ecb24daf66

I think it's good enough, but if you think there is something that not clear, you can again ask or create issue.

Thank you.

**Comment by archonwang** [comment]
@eckucukoglu , thanks so much.
