### ISSUE TITLE
Reminder script

### ISSUE THREAD

**Issue by npofopr** [eckucukoglu/redmine-reminder-emails#10]
Where to find reminder script?
Or should I write it? 😃 
Maybe there are examples this script?

**Comment by eckucukoglu** [comment]
Script is written by plugin to the path "script/redmine_due_reminder.sh" by default. You do not need to do anything to create it.

However you can change the path from plugin settings.

Example content for script (that was also generated by plugin, not manually): 
`#!/bin/bash`
`cd /opt/redmine/releases/3.0`
`/home/redmine/.rvm/gems/ruby-2.0.0-p576/bin/rake redmine:send_reminders project="60" days="10" RAILS_ENV="production" users="80"`
`/home/redmine/.rvm/gems/ruby-2.0.0-p576/bin/rake redmine:send_reminders project="60" days="21" RAILS_ENV="production" tracker="13" users="80,691"`
