### ISSUE TITLE
Can I use it on Windows?

### ISSUE THREAD

**Issue by Vritomos** [eckucukoglu/redmine-reminder-emails#13]
Once the plugin was made to work with cron jobs, is there any way I can make it run on Windows? I'm running Bitnami Redmine 3.3.3 on Windows 8.1.

**Comment by eckucukoglu** [comment]
Hi @Vritomos,
cronjobs manage the scheduled jobs for you, so I'm sure there are alternatives for Windows, too.

Check that thread: https://stackoverflow.com/questions/7195503/setting-up-a-cron-job-in-windows
