### ISSUE TITLE
plugin settings: 404 error

### ISSUE THREAD

**Issue by byZARE** [eckucukoglu/redmine-reminder-emails#7]
Hello there

I installed the plugin but it has some bugs in it.
First when I want to configure a project there is translation missing.
![capture](https://cloud.githubusercontent.com/assets/20943212/17962477/5ba45132-6ab1-11e6-86d7-b847379806af.PNG)
Second when I want to configure the plugin in administration I get 404 errror
![capture2](https://cloud.githubusercontent.com/assets/20943212/17962480/60d742c2-6ab1-11e6-89cd-9997175d425b.PNG)

**Comment by byZARE** [comment]
If i get an english title I can translate it to german.

**Comment by eckucukoglu** [comment]
hi byzare,

actually there is an english localization file, https://github.com/eckucukoglu/redmine-reminder-emails/blob/master/config/locales/en.yml

if you can translate it to german and make pull request, i appreciate it. :+1:

**Comment by byZARE** [comment]
okay i will translate it till sunday 

but what about the other error? do you need log files?

**Comment by eckucukoglu** [comment]
moreover, afaik in case of localization file does not exist, english titles should be used? can you please give more information about issue.

about configuration 404 error, if you can share development logs i can investigate the problem. because currently /redmine/settings/plugin/reminderemails path directs to redmine/plugins/reminderemails/app/views/settings/_reminderemails.erb successfully. 

also w/ development logs, your redmine/rails/ruby versions help a lot to solve issue.

thanks a lot byzare.

**Comment by jtiance** [comment]
Hi eckucukoglu:
I met 404 error too. Here is the log:
Started GET "/redmine/settings/plugin/reminderemails" for 127.0.0.1 at 2016-09-05 15:13:02 +0800
Processing by SettingsController#plugin as HTML
  Parameters: {"id"=>"reminderemails"}
  Current user: admin (id=1)
  Rendered settings/plugin.html.erb within layouts/admin (3.0ms)
Missing template, responding with 404
  Rendered common/error.html.erb within layouts/base (1.0ms)
Completed 404 Not Found in 60ms (Views: 9.0ms | ActiveRecord: 36.0ms)

I don't know the code, but I tried to find out plugin.html.erb, but I failed.

**Comment by eckucukoglu** [comment]
hi @jtiance ,

after 'current user' detection, this log is shown:
Rendered plugins/reminderemails/app/views/settings/_reminderemails.erb (1.1ms)

If file is missing (plugins/reminderemails/app/views/settings/_reminderemails.erb) system yields 500 error. So it can not be the case.

Currently, I do not know the reason behind the error. However, I want to ask questions to you;
1. Can you please specify your redmine/rails/ruby versions.
2. Can you please try new branch named '[bugfix_7](https://github.com/eckucukoglu/redmine-reminder-emails/tree/bugfix_7)'  and tell me if it works.
3. Do you have another plugins that plugin configuration settings work or not work properly?

**Comment by rurorani** [comment]
Hi @eckucukoglu,

Thanks so much for writing this great plugin.
I tried it but now have the same 404 error.

My OS: Ubuntu 14.04.3 LTS
My Redmine version: 3.1.2 (Bitnami)
My Rails version: 4.2.4
My Ruby version: ruby 2.0.0p647 (2015-08-18 revision 51631) [x86_64-linux]

About plugin install:
I downloaded the redmine-reminder-emails-0.0.1.zip, and unzipped it to redmin plugin folder:
[/opt/redmine-3.1.2-0/apps/redmine/htdocs/plugins]

I found it needed Redmine 3.3.0, so I manually modified the [init.rb] file under this plugin folder:
[requires_redmine version_or_higher: '3.1.2']

Then I ran [rake redmine:plugins:migrate RAILS_ENV=production] and then restarted the web server:
[sudo /opt/redmine-3.1.2-0/apache2/bin/apachectl -k restart]

I then could access the Redmine and its Administration page.
After clicking "Plugins" then "Configure" under "Reminder E-mails plugin", I got a 404 error.

## By checking Redmine's log file at [/opt/redmine-3.1.2-0/apps/redmine/htdocs/log], I found the following error related:

Started HEAD "/redmine" for 127.0.0.1 at 2016-10-27 12:30:25 +0800
Started GET "/redmine/" for 172.23.46.133 at 2016-10-27 12:30:25 +0800
Processing by WelcomeController#index as HTML
Processing by WelcomeController#index as HTML
  Current user: henry (id=9)
  Current user: anonymous
Redirected to http://127.0.0.1/redmine/login?back_url=http%3A%2F%2F127.0.0.1%2Fredmine%2F
Filter chain halted as :check_if_login_required rendered or redirected
Completed 302 Found in 173ms (ActiveRecord: 3.1ms)
  Rendered news/_news.html.erb (22.4ms)
  Rendered welcome/index.html.erb within layouts/base (68.1ms)
Completed 200 OK in 529ms (Views: 327.5ms | ActiveRecord: 10.9ms)
Started GET "/redmine/admin" for 172.23.46.133 at 2016-10-27 12:30:28 +0800
Processing by AdminController#index as HTML
  Current user: henry (id=9)
  Rendered admin/_menu.html.erb (4.4ms)
  Rendered admin/index.html.erb within layouts/admin (30.6ms)
  Rendered layouts/base.html.erb (306.2ms)
Completed 200 OK in 357ms (Views: 338.0ms | ActiveRecord: 6.1ms)
Started GET "/redmine/admin/plugins" for 172.23.46.133 at 2016-10-27 12:30:30 +0800
Processing by AdminController#plugins as HTML
  Current user: henry (id=9)
  Rendered admin/plugins.html.erb within layouts/admin (2.8ms)
  Rendered admin/_menu.html.erb (3.2ms)
  Rendered layouts/base.html.erb (10.5ms)
Completed 200 OK in 24ms (Views: 17.9ms | ActiveRecord: 1.4ms)
Started GET "/redmine/settings/plugin/reminderemails" for 172.23.46.133 at 2016-10-27 12:30:32 +0800
Processing by SettingsController#plugin as HTML
  Parameters: {"id"=>"reminderemails"}
  Current user: henry (id=9)
  Rendered settings/plugin.html.erb within layouts/admin (3.2ms)
Missing template, responding with 404
  Rendered common/error.html.erb within layouts/base (0.6ms)
Completed 404 Not Found in 25ms (Views: 11.8ms | ActiveRecord: 2.2ms)

## infra@redmine:/opt/redmine-3.1.2-0/apps/redmine/htdocs/log$

By the way, I have another plugin [Redmine Work Time plugin] and I could configure it without problem.

Could you please check the error and give any suggestions?
(I am very new to Redmine and Ruby...)

Thank you.

**Comment by eckucukoglu** [comment]
@rurorani , @byZARE , @jtiance ,

can you please try to rename plugin folder as **reminderemails**, and inform me please.
this should almost certainly solve the issue. :)

**Comment by advokatb** [comment]
Got the same 404 error. Renaming plugin folder to **reminderemails** solved the problem. Thanks.

**Comment by rurorani** [comment]
@eckucukoglu 
Thanks a lot! The problem is now solved according to your advice!

Btw, I want to ask will it be possible to add a new feature to this plugin, that at every project's reminder setting page, add "User role" option.
The options' value can be retrieved from Redmine Role setting, plus "Issue owner".

For example, for one reminder, I can set the "Role to be reminded" to "Manager, Issue Owner".
If one issue is overdue, Reminder will send an email to its owner as well as his/her manager.

Of course, as per Redmine system's feature and limit, the Role setting is only effective for each individual project. I do hope Redmine can provide global role setting though.

**Comment by eckucukoglu** [comment]
@rurorani it is a great idea, however currently i'm not working with redmine.

if anyone wants to contribute, they are completely welcomed. moreover, if i find a proper time to enhance features of this plugin, i will certainly take into account your suggestion. 
Thank you. :)
